### ISSUE TITLE
[Add]: Token ABE

### ISSUE THREAD

**Issue by 2capablockchain** [scolcoin/tokenLists#3]
### Nombre Completo del Token

ABE

### Iniciales del Token

ABE

### Website

#

### Datos de contacto

2capablockchain@gmail.com

### Contract Address

0x5d7bBef116733A7F52538689CCeafce4Eb31FEe7

### Url del Logo

https://github.com/scolcoin/tokenLists/blob/main/images/tokens/0x5d7bBef116733A7F52538689CCeafce4Eb31FEe7.png

**Comment by scolcoin** [comment]
ok agregado
